
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    mobizt/Firebase ESP32 Client
    adafruit/Adafruit BMP085 Library
    adafruit/Adafruit Unified Sensor
    milesburton/DallasTemperature
    paulstoffregen/OneWire
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
